apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-provider-opentofu
  namespace: flux-system
spec:
  interval: 10m
  path: ./infra/crossplane/providers/provider-opentofu/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  timeout: 5m
  dependsOn:
    - name: crossplane
      namespace: flux-system
    