apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helmrepos
  namespace: flux-system
spec:
  path: ./helmrepos
  interval: 20m
  timeout: 1m
  retryInterval: 30s
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: flux-system
