apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: microservices
  namespace: flux-system
spec:
  path: ./microservices
  interval: 20m0s
  timeout: 5m
  retryInterval: 1m0s
  prune: true
  force: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: infra
  decryption:
    provider: sops  # de esta forma fluxcd puede usar sops
  postBuild:
    substitute:
      namespace: staging
