apiVersion: aws.m.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-ivanhernanz
  namespace: team-frontend            # <- OBLIGATORIO (namespaced)
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: team-frontend #cambiar ek namespcae al del Namespaced
      name: aws-secret-ivanhernanz
      key: creds