apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-aws-s3-sa
  namespace: crossplane-system
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-aws-s3-rc
spec:
  serviceAccountTemplate:
    metadata:
      name: provider-aws-s3-sa
