apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  interval: 10m
  chart:
    spec:
      chart: crossplane
      sourceRef:
        kind: HelmRepository
        name: crossplane-stable
        namespace: flux-system
      # Opcionalmente puedes fijar versión del chart si quieres pinning estricto:
      # version: ">=2.0.0-0"  # ajusta según tus políticas
  values: {}  # deja vacío por ahora; añadiremos ajustes más adelante si hace falta
