---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: provider-aws
  namespace: flux-system
spec:
  interval: 20m0s
  path: ./infra/crossplane/providers/provider-aws/base
  prune: true
  force: true
  wait: true
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: crossplane
    namespace: flux-system
  healthChecks:
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    name: upbound-provider-family-aws
    namespace: crossplane-system