---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: provider-aws
  namespace: flux-system
spec:
  interval: 10m
  path: ./infra/crossplane/providers/provider-aws/base
  prune: true
  force: true
  wait: true
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: crossplane
    namespace: flux-system