---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane
  namespace: flux-system
spec:
  interval: 20m0s
  retryInterval: 1m0s
  timeout: 5m
  path: ./infra/crossplane/core/base
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    name: crossplane
    namespace: crossplane-system

