apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-providerconfig-opentofu-ivanhernanz-eu-west-1
  namespace: flux-system
spec:
  interval: 10m
  path: ./infra/crossplane/providersconfig/opentofu/ivanhernanz/eu-west-1/base
  prune: true
  force: true
  wait: true
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: opentofu.upbound.io/v1beta1
      kind: ProviderConfig
      name: opentofu-providerconfig-ivanhernanz
      namespace: team-frontend
  dependsOn:
    - name: crossplane-provider-opentofu   # el Kustomization que instala el Provider
      namespace: flux-system
